kind: Cluster 
apiVersion: kind.x-k8s.io/v1aplpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
  - role: worker
    extraPortMappings:
    - containerPort: 30007
      hostPort: 30008
    - role: worker

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  spec:
    containers:
    - name: nginx
      image: quote-generator
      ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-Service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007 
  type: NodePort