apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quote-generator
  spec:
    containers:
    - name: quote-generator
      image: sameerrrrr/quote-api:latest
      ports:
      - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: quote-generator-service
spec:
  selector:
    app: quote-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer